**Imports**

In [ ]:
import numpy as np
import pandas as pd
from sklearn import neighbors,metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boots safety  class
0  vhigh  vhigh     2       2     small    low  unacc
1  vhigh  vhigh     2       2     small    med  unacc
2  vhigh  vhigh     2       2     small   high  unacc
3  vhigh  vhigh     2       2       med    low  unacc
4  vhigh  vhigh     2       2       med    med  unacc


In [ ]:
x = data[['buying','maint','safety']].values
    
y = data[['class']]
print(x,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


**converting the data**

In [ ]:
Le= LabelEncoder()
for i in range(len(x[0])):
    x[:,i] = Le.fit_transform(x[:,i])

print(x)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [ ]:
label_maping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

In [ ]:
y['class'] = y['class'].map(label_maping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-16-29790d81b735>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_maping)


**creat model**

In [ ]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2)

knn.fit(x_train,y_train)

prediction = knn.predict(x_test)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
accuracy= metrics.accuracy_score(y_test,prediction)
print("prediction: ", prediction)
print("accuracy: ", accuracy)
a =600
print("actual value: ", y[a])
print("predicted value: ", knn.predict(x)[a])

prediction:  [0 0 0 0 2 2 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 2 0 0 0 1 0 0
 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 3 0 0 0 0 0 3 0 0
 0 0 0 0 0 0 0 2 0 0 0 0 2 1 3 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0
 1 0 0 1 0 0 1 0 0 1 2 0 0 1 0 1 1 0 0 0 2 1 0 0 1 1 0 3 0 0 0 0 0 0 0 0 2
 0 0 0 3 0 2 0 2 0 0 0 0 3 0 0 0 1 0 0 1 1 2 0 0 0 1 0 3 0 0 0 0 2 0 0 0 0
 0 1 0 0 0 1 3 0 0 0 0 0 0 0 1 0 1 3 1 0 2 1 0 0 0 0 2 0 2 0 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 3 0 1 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 3 0 0 0 0 1 0 1 0 0 3 3 2 0 0 2 0 0 0 1 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 1 2 2 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 1 1
 0 0 0 0 0 1 1 0 0 0 0 0 0]
accuracy:  0.7398843930635838
actual value:  [0]
predicted value:  0
